name = "deja-admin"
compatibility_date = "2024-03-05"
pages_build_output_dir = "./dist"

# Development environment variables
[vars]
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuY2djdWNlanBtd3BqY3hkd2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MzQ0NDYsImV4cCI6MjA1NjQxMDQ0Nn0.sl1_S_PY0t_Y2cdN5s9nR4QDzdOkpxON8zEtKE_HNYY"
SUPABASE_URL = "https://vncgcucejpmwpjcxdwhd.supabase.co"

# Add development environment R2 configuration
[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'deja-cafe'

[env.preview]
ALLOW_REGISTRATION = "true"

# Production environment configuration
[env.production]
[[env.production.r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'deja-cafe'

# Production environment variables
[env.production.vars]
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuY2djdWNlanBtd3BqY3hkd2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MzQ0NDYsImV4cCI6MjA1NjQxMDQ0Nn0.sl1_S_PY0t_Y2cdN5s9nR4QDzdOkpxON8zEtKE_HNYY"
SUPABASE_URL = "https://vncgcucejpmwpjcxdwhd.supabase.co"
REACT_APP_API_BASE_URL = "/api"
ALLOW_REGISTRATION = "false"